spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres1}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5452/book-app}
    password: ${POSTGRES_PASSWORD:postgres1}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  main:
    allow-circular-references: true
server:
  port:
    8080
  error:
    include-message: always
    include-binding-errors: always