version: "3.3"

services:
  cloud_postgres:
    container_name: cloud_postgres
    image: "postgres:14"
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    ports:
      - 5437:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: business-logic
    build:
      context: .
    ports:
      - 8065:8080
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_URL: $POSTGRES_URL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
      - cloud_postgres